# Astronomer Airflow local settings: connections, pools, and variables.
# When running 'astro dev start', these connections are automatically provisioned.

airflow:
  connections:
    - conn_id: snowflake_default
      conn_type: snowflake
      conn_login: kkp007
      conn_password: peAivA6Vuh549XV
      conn_schema: RAW
      conn_extra:
        account: VVXMVZH-FL05366
        warehouse: ZOMATO_WH
        database: ZOMATO
        role: DBT_ROLE
        insecure_mode: false

  pools:
    - pool_name: default_pool
      pool_slot: 128
      pool_description: "Default execution pool"

  variables:
    - variable_name: dbt_project_path
      variable_value: /usr/local/airflow/zomato
