apiVersion: v1
kind: ConfigMap
metadata:
  name: mlops-config
  namespace: mlops-system
  labels:
    app: colorectal-cancer-app
    tier: production
data:
  APP_ENV: "production"
  PORT: "5000"
  MODEL_PATH: "/app/artifacts/models/model.pkl"
  SCALER_PATH: "/app/artifacts/processed/scaler.pkl"
  LOG_LEVEL: "INFO"
  MLFLOW_TRACKING_URI: "https://dagshub.com/kishorkumarparoi/AI-Engineering.mlflow"
  MLFLOW_EXPERIMENT_NAME: "colorectal-cancer-survival-prediction"
