apiVersion: v1
kind: Secret
metadata:
  name: mlops-secret
  namespace: mlops-system
  labels:
    app: colorectal-cancer-app
    tier: production
type: Opaque
stringData:
  MLFLOW_TRACKING_USERNAME: "kishorkumarparoi"
  MLFLOW_TRACKING_PASSWORD: "YOUR_DAGSHUB_TOKEN_OR_PASSWORD"
  DAGSHUB_USER_TOKEN: "YOUR_DAGSHUB_TOKEN"
